background_opacity 0.75
hide_window_decorations yes
active_border_color #d79921
inactive_border_color #3c3836


# BEGIN_KITTY_THEME
# Gruvbox Material Dark Hard
include current-theme.conf
# END_KITTY_THEME
